apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-podinfo
  namespace: argocd # Or the namespace where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo # Helm chart repository URL
    chart: podinfo
    targetRevision: 6.6.2 # Specify the desired chart version
    helm:
      values: |
        ui:
          message: "Hello from Argo CD!"
  destination:
    server: https://kubernetes.default.svc # Or the URL of your target cluster
    # namespace: podinfo # Namespace where podinfo will be deployed
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically create the target namespace if it doesn't exist